### ISSUE TITLE
Incorrect flag displayed for Ireland

### ISSUE THREAD

**Issue by IdlePhysicist** [stevenliuyi/covid19#49]
As the title says, the Irish flag is not being rendered. See photo below.

![ireland](https://user-images.githubusercontent.com/20644761/83151410-71353c00-a0f4-11ea-8d7c-0df98b3207df.png)

**Comment by damiansf** [comment]
This is just an issue in the HTML for that dropdown. The flag pack the project uses is flag-icon-css, this uses https://www.iso.org/obp/ui/#search to get country 2 letter identifiers for the various flags. If you inspect the Irish flag in the running app "flag-icon-ir" (which is for Iran) is used instead of "flag-icon-ie" (Ireland). Ill open a PR with the fix soon

**Comment by damiansf** [comment]
@IdlePhysicist @stevenliuyi PR is merged now with the fix. The ticket can be closed now

**Comment by IdlePhysicist** [comment]
Speedy fix, fair play!
